### ISSUE TITLE
Container crashes when trying to register a new user

### ISSUE THREAD

**Issue by A-wels** [ThreeHats/foundryvtt-rest-api#6]
When trying to register a new user on a selfhosted container, I get the error:
``` 
foundryrelay  | Registration attempt for: foundryvtt@test.de
foundryrelay  | Creating new user...
foundryrelay  | Registration error: TypeError: Cannot read properties of undefined (reading 'length')
foundryrelay  |     at User._initValues (/app/node_modules/.pnpm/sequelize@6.37.7_pg@8.16.0_sqlite3@5.1.7/node_modules/sequelize/src/model.js:164:49)
foundryrelay  |     at new Model (/app/node_modules/.pnpm/sequelize@6.37.7_pg@8.16.0_sqlite3@5.1.7/node_modules/sequelize/src/model.js:142:10)
foundryrelay  |     at new User (/app/src/models/user.ts:9:8)
foundryrelay  |     at Function.build (/app/node_modules/.pnpm/sequelize@6.37.7_pg@8.16.0_sqlite3@5.1.7/node_modules/sequelize/src/model.js:2255:12)
foundryrelay  |     at Function.create (/app/node_modules/.pnpm/sequelize@6.37.7_pg@8.16.0_sqlite3@5.1.7/node_modules/sequelize/src/model.js:2305:23)
foundryrelay  |     at <anonymous> (/app/src/routes/api.ts:240:31)
foundryrelay  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
foundryrelay  | 2025-06-15T16:22:48.363Z [info]: SanitizeResponse: Removed 0 sensitive keys.
foundryrelay  | /app/node_modules/.pnpm/sequelize@6.37.7_pg@8.16.0_sqlite3@5.1.7/node_modules/sequelize/src/model.js:95
foundryrelay  |         for (const key of Object.keys(this.constructor._attributeManipulation)) {
foundryrelay  |                                  ^
foundryrelay  |
foundryrelay  |
foundryrelay  | TypeError: Cannot convert undefined or null to object
foundryrelay  |     at Function.keys (<anonymous>)
foundryrelay  |     at Timeout._onTimeout (/app/node_modules/.pnpm/sequelize@6.37.7_pg@8.16.0_sqlite3@5.1.7/node_modules/sequelize/src/model.js:95:34)
foundryrelay  |     at listOnTimeout (node:internal/timers:581:17)
foundryrelay  |     at process.processTimers (node:internal/timers:519:7)
foundryrelay  |
foundryrelay  | Node.js v20.19.2
```

This is my docker compose section:
```
  foundryrelay:
    image: threehats/foundryvtt-rest-api-relay:latest
    container_name: foundryrelay
    restart: always
    mem_limit: 512m
    hostname: foundryrelay
    # Commented we use the port on the proxy
    ports:
      - "33010:3010"
    environment:
      - NODE_ENV=production
      - PORT=3010
    volumes:
      - ./data/relay:/app/data
    command: pnpm local
```
